### ISSUE TITLE
Problem with using directional method "PREDICTED"

### ISSUE THREAD

**Issue by SiduoLi2020** [MPI-Dortmund/cryolo#19]
Hello!
I use crYOLO for filament picking. I have chosen "_Activate filament mode_" and the crYOLO model. Although there were no errors when I was running predictions, the log indicates that I can't use the directional method "PREDICTED":

##########
The directional method "PREDICTED" can't be used as your model is not a filament model.You need to retrain your picking model. Fall back to old directional method "CONVOLUTION".
##########

How to use directional method "PREDICTED"? Also I want to konw weather _PREDICTED_ is more precise than _CONVOLUTION_  ?

By the way, tutorials document of  Install napari and the boxmanager plugin is incorrect.  I cannot install napari by conda while the command  `pip install napari`  can work. :)

**Comment by thorstenwagner** [comment]
Hi,

thanks for getting in touch :-) 

> How to use directional method "PREDICTED"? 

how did you train the crYOLO model? You need to train with filament annotations to get a filament model which can use "PREDICTED". The general model is only for single particles.

> "How to use directional method "PREDICTED"? Also I want to know weather PREDICTED is more precise than CONVOLUTION 

I didn't do a systematic comparison, but PREDICTED should be more flexible regarding the filament shape. CONVOLUTION expects that the filament has certain width.

> By the way, tutorials document of Install napari and the boxmanager plugin is incorrect. I cannot install napari by conda while the command pip install napari can work. :)

Can you tell me what kind of error you saw? I just redid the installation as described in the tutorial and its working on my side.

Best,
Thorsten

**Comment by SiduoLi2020** [comment]
Thanks for your response! Perhaps the napari is  cause of all problems.

>  Can you tell me what kind of error you saw? I just redid the installation as described in the tutorial and its working on my side.

I still cannot install napari by conda.  Here is the log.

`conda create -y -n napari-cryolo -c conda-forge python=3.10 napari=0.4.17 pyqt pip`
`An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
If your current network has https://repo.anaconda.com blocked, please file
a support request with your network engineering team.
'https//repo.anaconda.com/pkgs/main/linux-64'`

I also tried download napari in dependent , it stopped in _solving enviromnet_.
```shell
conda install -c conda-forge napari=0.4.17`
Collecting package metadata (current_repodata.json): / DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): conda.anaconda.org:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): conda.anaconda.org:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443                                                                                                                      
DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/r/linux-64/current_repodata.json HTTP/1.1" 304 0                                                                                      | DEBUG:urllib3.connectionpool:https://conda.anaconda.org:443 "GET /conda-forge/noarch/current_repodata.json HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://conda.anaconda.org:443 "GET /conda-forge/linux-64/current_repodata.json HTTP/1.1" 200 None                                                                             - DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/main/noarch/current_repodata.json HTTP/1.1" 304 0                                                                                     - DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/main/linux-64/current_repodata.json HTTP/1.1" 304 0                                                                                   
DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/r/noarch/current_repodata.json HTTP/1.1" 304 0                                                                                        done
Solving environment: unsuccessful initial attempt using frozen solve. Retrying with flexible solve.
Solving environment: unsuccessful attempt using repodata from current_repodata.json, retrying with next repodata source.
Collecting package metadata (repodata.json): | DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): conda.anaconda.org:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): conda.anaconda.org:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443                                                                                                                       DEBUG:urllib3.connectionpool:https://conda.anaconda.org:443 "GET /conda-forge/noarch/repodata.json HTTP/1.1" 200 None                                                                                       DEBUG:urllib3.connectionpool:https://conda.anaconda.org:443 "GET /conda-forge/linux-64/repodata.json HTTP/1.1" 200 None                                                                                     DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/main/linux-64/repodata.json HTTP/1.1" 304 0
DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/r/linux-64/repodata.json HTTP/1.1" 304 0                                                                                              | DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/main/noarch/repodata.json HTTP/1.1" 304 0                                                                                             / DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/r/noarch/repodata.json HTTP/1.1" 304 0                                                                                                done
Solving environment: \
```

I'm not sure if all this is caused by network issues or the absence of this package on conda：
```shell
conda install napari`
PackagesNotFoundError: The following packages are not available from current channels:
- napari
```

Finally I try to download it by pip, thanksfully it works. （napari 0.4.18）

> how did you train the crYOLO model? You need to train with filament annotations to get a filament model which can use "PREDICTED". The general model is only for single particles.

**Is it because I deleted so many things that cryolo can't recognize the training data as filament?** 

Maybe the napari installed from pip have some bug. I cannot load .cox data into CRYOLO when i start trainning.

```shell
#####################################################
Important debugging information.
In case of any problems, please provide this information.
#####################################################
/home/em/anaconda3/envs/cryolo/bin/cryolo_gui.py train 
-c config_cryolo.json 
-w 5 
-nc 16 
--gpu_fraction 1.0 
-e 10 
-lft 2 
--seed 10 
#####################################################
###############################################
New version of crYOLO available
Local version:		 1.8.4
Latest version:		 1.9.6
More information here:
 https://cryolo.readthedocs.io/en/latest/changes.html
###############################################
###############################################
The following training image sizes were detected:
4096 x 4096 ( N: 19 )

crYOLO will train in mode: SQUARE
###############################################
Reading old CBOX format file

2023-09-28 22:37:44.408501: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.
Using TensorFlow backend.
2023-09-28 22:37:45.391510: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2000000000 Hz
2023-09-28 22:37:45.392759: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55c37ef32190 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2023-09-28 22:37:45.392783: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2023-09-28 22:37:45.396331: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcuda.so.1
2023-09-28 22:37:45.632035: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55c37e424c40 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2023-09-28 22:37:45.632077: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): NVIDIA GeForce RTX 2080 Ti, Compute Capability 7.5
2023-09-28 22:37:45.633273: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1666] Found device 0 with properties:
name: NVIDIA GeForce RTX 2080 Ti major: 7 minor: 5 memoryClockRate(GHz): 1.545
pciBusID: 0000:1a:00.0
2023-09-28 22:37:45.633341: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2023-09-28 22:37:45.645550: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.11
2023-09-28 22:37:45.674337: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcufft.so.10
2023-09-28 22:37:45.674665: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcurand.so.10
2023-09-28 22:37:45.675267: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusolver.so.11
2023-09-28 22:37:45.676324: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusparse.so.11
2023-09-28 22:37:45.676471: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.8
2023-09-28 22:37:45.678536: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1794] Adding visible gpu devices: 0
2023-09-28 22:37:45.678600: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2023-09-28 22:37:46.174525: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1206] Device interconnect StreamExecutor with strength 1 edge matrix:
2023-09-28 22:37:46.174567: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1212]      0
2023-09-28 22:37:46.174575: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1225] 0:   N
2023-09-28 22:37:46.176901: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1351] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6624 MB memory) -> physical GPU (device: 0, name: NVIDIA GeForce RTX 2080 Ti, pci bus id: 0000:1a:00.0, compute capability: 7.5)
Traceback (most recent call last):
  File "/home/em/anaconda3/envs/cryolo/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 2895, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1675, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: '_CoordinateZ'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/em/anaconda3/envs/cryolo/lib/python3.8/site-packages/cryolo/CoordsIO.py", line 230, in read_cbox_boxfile
    z=starfile['cryolo']['_CoordinateZ'][i],
  File "/home/em/anaconda3/envs/cryolo/lib/python3.8/site-packages/pandas/core/frame.py", line 2906, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/em/anaconda3/envs/cryolo/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 2897, in get_loc
    raise KeyError(key) from err
KeyError: '_CoordinateZ'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/em/anaconda3/envs/cryolo/bin/cryolo_gui.py", line 8, in <module>
    sys.exit(_main_())
  File "/home/em/anaconda3/envs/cryolo/lib/python3.8/site-packages/cryolo/cryolo_main.py", line 455, in _main_
    Gooey(
  File "/home/em/anaconda3/envs/cryolo/lib/python3.8/site-packages/gooey/python_bindings/gooey_decorator.py", line 134, in <lambda>
    return lambda *args, **kwargs: func(*args, **kwargs)
  File "/home/em/anaconda3/envs/cryolo/lib/python3.8/site-packages/cryolo/cryolo_main.py", line 424, in main
    train.main(args)
  File "/home/em/anaconda3/envs/cryolo/lib/python3.8/site-packages/cryolo/train.py", line 516, in main
    parse_dict = preprocess.parse_annotation(
  File "/home/em/anaconda3/envs/cryolo/lib/python3.8/site-packages/cryolo/preprocessing.py", line 150, in parse_annotation
    filaments = CoordsIO.read_cbox_boxfile(boxpath, int(cell_h))
  File "/home/em/anaconda3/envs/cryolo/lib/python3.8/site-packages/cryolo/CoordsIO.py", line 265, in read_cbox_boxfile
    return read_cbox_boxfile_old(path)
  File "/home/em/anaconda3/envs/cryolo/lib/python3.8/site-packages/cryolo/CoordsIO.py", line 273, in read_cbox_boxfile_old
    boxreader = np.atleast_2d(np.genfromtxt(path))
  File "/home/em/anaconda3/envs/cryolo/lib/python3.8/site-packages/numpy/lib/npyio.py", line 2103, in genfromtxt
    raise ValueError(errmsg)
ValueError: Some errors were detected !
    Line #3 (got 2 columns instead of 1)
    Line #13 (got 5 columns instead of 1)
    Line #14 (got 5 columns instead of 1)
    Line #15 (got 5 columns instead of 1)
    Line #16 (got 5 columns instead of 1)
    Line #17 (got 5 columns instead of 1)
    Line #18 (got 5 columns instead of 1)
    Line #19 (got 5 columns instead of 1)
    Line #20 (got 5 columns instead of 1)
    Line #21 (got 5 columns instead of 1)
    Line #22 (got 5 columns instead of 1)
    Line #23 (got 5 columns instead of 1)
    Line #24 (got 5 columns instead of 1)
    Line #25 (got 5 columns instead of 1)
    Line #26 (got 5 columns instead of 1)
    Line #27 (got 5 columns instead of 1)
    Line #28 (got 5 columns instead of 1)
    Line #38 (got 5 columns instead of 1)
    Line #39 (got 5 columns instead of 1)
    Line #40 (got 5 columns instead of 1)
    Line #41 (got 5 columns instead of 1)
    Line #42 (got 5 columns instead of 1)
    Line #43 (got 5 columns instead of 1)
    Line #44 (got 5 columns instead of 1)
    Line #45 (got 5 columns instead of 1)
    Line #46 (got 5 columns instead of 1)
    Line #47 (got 5 columns instead of 1)
    Line #48 (got 5 columns instead of 1)
    Line #49 (got 5 columns instead of 1)
    Line #50 (got 5 columns instead of 1)
    Line #51 (got 5 columns instead of 1)
    Line #52 (got 5 columns instead of 1)
    Line #53 (got 5 columns instead of 1)
    Line #54 (got 5 columns instead of 1)
    Line #55 (got 5 columns instead of 1)
    Line #56 (got 5 columns instead of 1)
    Line #57 (got 5 columns instead of 1)
    Line #58 (got 5 columns instead of 1)
    Line #59 (got 5 columns instead of 1)
    Line #60 (got 5 columns instead of 1)
    Line #61 (got 5 columns instead of 1)
    Line #62 (got 5 columns instead of 1)
    Line #63 (got 5 columns instead of 1)
    Line #64 (got 5 columns instead of 1)
    Line #65 (got 5 columns instead of 1)
    Line #66 (got 5 columns instead of 1)
    Line #67 (got 5 columns instead of 1)
    Line #68 (got 5 columns instead of 1)
    Line #69 (got 5 columns instead of 1)
    Line #70 (got 5 columns instead of 1)
    Line #71 (got 5 columns instead of 1)
    Line #72 (got 5 columns instead of 1)
    Line #73 (got 5 columns instead of 1)
    Line #74 (got 5 columns instead of 1)
    Line #75 (got 5 columns instead of 1)
    Line #76 (got 5 columns instead of 1)
    Line #77 (got 5 columns instead of 1)
    Line #78 (got 5 columns instead of 1)
    Line #79 (got 5 columns instead of 1)
    Line #80 (got 5 columns instead of 1)
    Line #81 (got 5 columns instead of 1)
    Line #82 (got 5 columns instead of 1)
    Line #83 (got 5 columns instead of 1)
    Line #84 (got 5 columns instead of 1)
    Line #85 (got 5 columns instead of 1)
    Line #86 (got 5 columns instead of 1)
    Line #87 (got 5 columns instead of 1)
    Line #88 (got 5 columns instead of 1)
    Line #89 (got 5 columns instead of 1)
    Line #90 (got 5 columns instead of 1)
    Line #91 (got 5 columns instead of 1)
    Line #92 (got 5 columns instead of 1)
    Line #93 (got 5 columns instead of 1)
    Line #94 (got 5 columns instead of 1)
    Line #95 (got 5 columns instead of 1)
    Line #96 (got 5 columns instead of 1)
    Line #97 (got 5 columns instead of 1)
    Line #98 (got 5 columns instead of 1)
    Line #99 (got 5 columns instead of 1)
    Line #100 (got 5 columns instead of 1)
    Line #101 (got 5 columns instead of 1)
    Line #102 (got 5 columns instead of 1)
    Line #103 (got 5 columns instead of 1)
    Line #104 (got 5 columns instead of 1)
    Line #105 (got 5 columns instead of 1)
    Line #106 (got 5 columns instead of 1)
    Line #107 (got 5 columns instead of 1)
    Line #108 (got 5 columns instead of 1)
    Line #109 (got 5 columns instead of 1)
    Line #110 (got 5 columns instead of 1)
    Line #111 (got 5 columns instead of 1)
    Line #112 (got 5 columns instead of 1)
    Line #113 (got 5 columns instead of 1)
    Line #114 (got 5 columns instead of 1)
    Line #115 (got 5 columns instead of 1)
    Line #116 (got 5 columns instead of 1)
    Line #117 (got 5 columns instead of 1)
    Line #118 (got 5 columns instead of 1)
    Line #119 (got 5 columns instead of 1)

``` 

I check the .cox file：
```

data_global

_cbox_format_version   1.0 

data_filament_vertices

loop_
_CoordinateX #1
_CoordinateY #2
_filamentid #3
_Width #4
_Height #5
 1167.069071  1648.989192  0.000000  500.000000  500.000000 
  221.764288   235.665864  0.000000  500.000000  500.000000 
 1709.229167  1384.859914  1.000000  500.000000  500.000000 
 2585.026245   175.425853  1.000000  500.000000  500.000000 
 1139.265989   370.047426  2.000000  500.000000  500.000000 
 1343.155256   193.961241  2.000000  500.000000  500.000000 
 2306.995427  1964.090786  3.000000  500.000000  500.000000 
 4007.617267  1556.312252  3.000000  500.000000  500.000000 
 1199.506000  2724.041690  4.000000  500.000000  500.000000 
 1273.647551  4021.518843  4.000000  500.000000  500.000000 
  471.992024  2612.829363  5.000000  500.000000  500.000000 
  967.813651  3993.715761  5.000000  500.000000  500.000000 
 1662.890697  2413.573943  6.000000  500.000000  500.000000 
 2793.549359  2700.872455  6.000000  500.000000  500.000000 
  921.475181  2571.124740  7.000000  500.000000  500.000000 
 2093.838466  3919.574210  7.000000  500.000000  500.000000 

data_cryolo

loop_
_CoordinateX #1
_CoordinateY #2
_filamentid #3
_Width #4
_Height #5
 1398.989192   917.069071  0.000000  500.000000  500.000000 
 1281.212248   838.293672  0.000000  500.000000  500.000000 
 1163.435304   759.518274  0.000000  500.000000  500.000000 
 1045.658360   680.742875  0.000000  500.000000  500.000000 
  927.881416   601.967476  0.000000  500.000000  500.000000 
  810.104472   523.192078  0.000000  500.000000  500.000000 
  692.327528   444.416679  0.000000  500.000000  500.000000 
  574.550584   365.641281  0.000000  500.000000  500.000000 
  456.773640   286.865882  0.000000  500.000000  500.000000 
  338.996696   208.090484  0.000000  500.000000  500.000000 
  221.219752   129.315085  0.000000  500.000000  500.000000 
  103.442808    50.539686  0.000000  500.000000  500.000000 
  -14.334136   -28.235712  0.000000  500.000000  500.000000 
 1134.859914  1459.229167  1.000000  500.000000  500.000000 
 1013.916508  1546.808875  1.000000  500.000000  500.000000 
  892.973102  1634.388583  1.000000  500.000000  500.000000 
  772.029696  1721.968290  1.000000  500.000000  500.000000 
  651.086290  1809.547998  1.000000  500.000000  500.000000 
  530.142884  1897.127706  1.000000  500.000000  500.000000 
  409.199478  1984.707414  1.000000  500.000000  500.000000 
  288.256072  2072.287122  1.000000  500.000000  500.000000 
  167.312666  2159.866830  1.000000  500.000000  500.000000 
   46.369259  2247.446538  1.000000  500.000000  500.000000 
  -74.574147  2335.026245  1.000000  500.000000  500.000000 
  120.047426   889.265989  2.000000  500.000000  500.000000 
  -56.038759  1093.155256  2.000000  500.000000  500.000000 
 1714.090786  2056.995427  3.000000  500.000000  500.000000 
 1680.109242  2198.713914  3.000000  500.000000  500.000000 
 1646.127697  2340.432400  3.000000  500.000000  500.000000 
 1612.146153  2482.150887  3.000000  500.000000  500.000000 
 1578.164608  2623.869374  3.000000  500.000000  500.000000 
 1544.183064  2765.587860  3.000000  500.000000  500.000000 
 1510.201519  2907.306347  3.000000  500.000000  500.000000 
 1476.219975  3049.024834  3.000000  500.000000  500.000000 
 1442.238430  3190.743320  3.000000  500.000000  500.000000 
 1408.256886  3332.461807  3.000000  500.000000  500.000000 
 1374.275341  3474.180294  3.000000  500.000000  500.000000 
 1340.293797  3615.898780  3.000000  500.000000  500.000000 
 1306.312252  3757.617267  3.000000  500.000000  500.000000 
 2474.041690   949.506000  4.000000  500.000000  500.000000 
 2618.205818   957.743950  4.000000  500.000000  500.000000 
 2762.369946   965.981900  4.000000  500.000000  500.000000 
 2906.534074   974.219850  4.000000  500.000000  500.000000 
 3050.698203   982.457800  4.000000  500.000000  500.000000 
 3194.862331   990.695751  4.000000  500.000000  500.000000 
 3339.026459   998.933701  4.000000  500.000000  500.000000 
 3483.190587  1007.171651  4.000000  500.000000  500.000000 
 3627.354715  1015.409601  4.000000  500.000000  500.000000 
 3771.518843  1023.647551  4.000000  500.000000  500.000000 
 2362.829363   221.992024  5.000000  500.000000  500.000000 
 2500.918002   271.574187  5.000000  500.000000  500.000000 
 2639.006642   321.156350  5.000000  500.000000  500.000000 
 2777.095282   370.738512  5.000000  500.000000  500.000000 
 2915.183922   420.320675  5.000000  500.000000  500.000000 
 3053.272562   469.902838  5.000000  500.000000  500.000000 
 3191.361202   519.485000  5.000000  500.000000  500.000000 
 3329.449842   569.067163  5.000000  500.000000  500.000000 
 3467.538482   618.649326  5.000000  500.000000  500.000000 
 3605.627121   668.231488  5.000000  500.000000  500.000000 
 3743.715761   717.813651  5.000000  500.000000  500.000000 
 2163.573943  1412.890697  6.000000  500.000000  500.000000 
 2199.486257  1554.223030  6.000000  500.000000  500.000000 
 2235.398571  1695.555363  6.000000  500.000000  500.000000 
 2271.310885  1836.887695  6.000000  500.000000  500.000000 
 2307.223199  1978.220028  6.000000  500.000000  500.000000 
 2343.135513  2119.552361  6.000000  500.000000  500.000000 
 2379.047827  2260.884694  6.000000  500.000000  500.000000 
 2414.960141  2402.217027  6.000000  500.000000  500.000000 
 2450.872455  2543.549359  6.000000  500.000000  500.000000 
 2321.124740   671.475181  7.000000  500.000000  500.000000 
 2433.495529   769.172122  7.000000  500.000000  500.000000 
 2545.866318   866.869062  7.000000  500.000000  500.000000 
 2658.237107   964.566002  7.000000  500.000000  500.000000 
 2770.607896  1062.262943  7.000000  500.000000  500.000000 
 2882.978686  1159.959883  7.000000  500.000000  500.000000 
 2995.349475  1257.656824  7.000000  500.000000  500.000000 
 3107.720264  1355.353764  7.000000  500.000000  500.000000 
 3220.091053  1453.050704  7.000000  500.000000  500.000000 
 3332.461842  1550.747645  7.000000  500.000000  500.000000 
 3444.832631  1648.444585  7.000000  500.000000  500.000000 
 3557.203421  1746.141526  7.000000  500.000000  500.000000 
 3669.574210  1843.838466  7.000000  500.000000  500.000000 

data_cryolo_include

loop_
_slice_index #1

``` 

I changed the format, keeping only the X and Y coordinates of the box and the size of the box：
```
1398.989192	917.0690710000001	500.0	500.0
1281.212248	838.293672	500.0	500.0
1163.4353039999999	759.518274	500.0	500.0
1045.65836	680.742875	500.0	500.0
927.8814160000001	601.967476	500.0	500.0
810.104472	523.192078	500.0	500.0
692.327528	444.416679	500.0	500.0
574.550584	365.641281	500.0	500.0
456.77364000000006	286.865882	500.0	500.0
338.996696	208.090484	500.0	500.0
221.219752	129.315085	500.0	500.0
103.442808	50.539685999999996	500.0	500.0
-14.334135999999999	-28.235712	500.0	500.0
1134.8599140000001	1459.229167	500.0	500.0
1013.916508	1546.808875	500.0	500.0
892.9731019999999	1634.388583	500.0	500.0
772.029696	1721.9682899999998	500.0	500.0
651.0862900000001	1809.547998	500.0	500.0
530.142884	1897.1277059999998	500.0	500.0
409.199478	1984.707414	500.0	500.0
288.256072	2072.2871219999997	500.0	500.0
167.31266599999998	2159.86683	500.0	500.0
46.369259	2247.4465379999997	500.0	500.0
-74.574147	2335.026245	500.0	500.0
120.047426	889.2659890000001	500.0	500.0
-56.038759	1093.155256	500.0	500.0
1714.090786	2056.995427	500.0	500.0
1680.1092420000002	2198.713914	500.0	500.0
1646.1276970000001	2340.4324	500.0	500.0
1612.146153	2482.1508870000002	500.0	500.0
1578.164608	2623.869374	500.0	500.0
1544.183064	2765.58786	500.0	500.0
1510.201519	2907.3063469999997	500.0	500.0
1476.219975	3049.024834	500.0	500.0
1442.23843	3190.74332	500.0	500.0
1408.256886	3332.461807	500.0	500.0
1374.275341	3474.180294	500.0	500.0
1340.293797	3615.8987799999995	500.0	500.0
1306.312252	3757.617267	500.0	500.0
2474.04169	949.506	500.0	500.0
2618.205818	957.74395	500.0	500.0
2762.3699460000003	965.9819	500.0	500.0
2906.5340739999997	974.21985	500.0	500.0
3050.698203	982.4578	500.0	500.0
3194.862331	990.695751	500.0	500.0
3339.026459	998.9337009999999	500.0	500.0
3483.1905869999996	1007.171651	500.0	500.0
3627.354715	1015.409601	500.0	500.0
3771.518843	1023.647551	500.0	500.0
2362.829363	221.99202400000001	500.0	500.0
2500.918002	271.574187	500.0	500.0
2639.0066420000003	321.15635	500.0	500.0
2777.095282	370.738512	500.0	500.0
2915.1839219999997	420.320675	500.0	500.0
3053.272562	469.902838	500.0	500.0
3191.361202	519.485	500.0	500.0
3329.449842	569.0671629999999	500.0	500.0
3467.538482	618.649326	500.0	500.0
3605.627121	668.231488	500.0	500.0
3743.715761	717.8136509999999	500.0	500.0
2163.573943	1412.890697	500.0	500.0
2199.486257	1554.22303	500.0	500.0
2235.398571	1695.555363	500.0	500.0
2271.3108850000003	1836.887695	500.0	500.0
2307.223199	1978.2200280000002	500.0	500.0
2343.1355129999997	2119.552361	500.0	500.0
2379.047827	2260.8846940000003	500.0	500.0
2414.960141	2402.217027	500.0	500.0
2450.872455	2543.549359	500.0	500.0
2321.1247399999997	671.4751809999999	500.0	500.0
2433.495529	769.172122	500.0	500.0
2545.866318	866.8690619999999	500.0	500.0
2658.237107	964.5660019999999	500.0	500.0
2770.607896	1062.262943	500.0	500.0
2882.978686	1159.959883	500.0	500.0
2995.349475	1257.656824	500.0	500.0
3107.720264	1355.353764	500.0	500.0
3220.091053	1453.050704	500.0	500.0
3332.461842	1550.747645	500.0	500.0
3444.832631	1648.444585	500.0	500.0
3557.203421	1746.141526	500.0	500.0
3669.57421	1843.838466	500.0	500.0
```

With the new format, cryolo train can work.
