### ISSUE TITLE
Error Training Cryolo Model on Multiple GPUs

### ISSUE THREAD

**Issue by barureddy** [MPI-Dortmund/cryolo#2]
I'm using cryolo (1.7.2) through sbgrid on multiple gpus (0 1 2 3) and it fails with the following error:

Traceback (most recent call last):
  File "/programs/x86_64-linux/cryolo/1.7.2/cryolo/bin/cryolo_gui.py", line 8, in <module>
    sys.exit(_main_())
  File "/programs/x86_64-linux/cryolo/1.7.2/cryolo_extlib/miniconda3-4.7.12.1-2tlz/lib/python3.6/site-packages/cryolo/cryolo_main.py", line 458, in _main_
    **kwargs
  File "/programs/x86_64-linux/cryolo/1.7.2/cryolo_extlib/miniconda3-4.7.12.1-2tlz/lib/python3.6/site-packages/gooey/python_bindings/gooey_decorator.py", line 93, in <lambda>
    return lambda *args, **kwargs: func(*args, **kwargs)
  File "/programs/x86_64-linux/cryolo/1.7.2/cryolo_extlib/miniconda3-4.7.12.1-2tlz/lib/python3.6/site-packages/cryolo/cryolo_main.py", line 419, in main
    train.main(args)
  File "/programs/x86_64-linux/cryolo/1.7.2/cryolo_extlib/miniconda3-4.7.12.1-2tlz/lib/python3.6/site-packages/cryolo/train.py", line 721, in main
    normalization=normalization_string
  File "/programs/x86_64-linux/cryolo/1.7.2/cryolo_extlib/miniconda3-4.7.12.1-2tlz/lib/python3.6/site-packages/cryolo/frontend.py", line 949, in train
    period=1,
  File "/programs/x86_64-linux/cryolo/1.7.2/cryolo_extlib/miniconda3-4.7.12.1-2tlz/lib/python3.6/site-packages/cryolo/MultiGPUModelCheckpoint.py", line 25, in __init__
    self.anchors - None
AttributeError: 'MultiGPUModelCheckpoint' object has no attribute 'anchors'

**Comment by barureddy** [comment]
Never mind see it has been fixed in 1.7.3
